#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const checks = [];

function check(name, ok) {
  checks.push({ name, ok: Boolean(ok) });
}

const css = read('css/style.css');
const productCss = read('css/products.css');
const nav = read('js/nav.js');
const main = read('js/main.js');
const products = read('products.html');
const productPageJs = read('js/products-page.js');
const productRuntime = products + '\n' + productPageJs;
const pages = [
  'index.html',
  'about.html',
  'products.html',
  'applications.html',
  'downloads.html',
  'distributors.html',
  'contact.html',
  '404.html'
];

pages.forEach(page => {
  const html = read(page);
  check(`${page} loads shared nav`, /<script src="\/js\/nav\.js(?:\?[^"']*)?"><\/script>/.test(html));
  check(`${page} has mobile nav container`, html.includes('class="nav-mobile"'));
  check(`${page} has hamburger`, html.includes('class="nav-hamburger"'));
});

check('mobile actions are generated by nav.js', /nav-mobile-actions/.test(nav) && /icon\('cart'\)/.test(nav) && /Get a Quote/.test(nav));
check('sticky mobile quote bar is generated by nav.js', /mobile-quote-bar/.test(nav) && /mobile-quote-count/.test(nav) && /View Quote/.test(nav));
check('mobile actions display at phone breakpoint', /@media \(max-width: 768px\)[\s\S]*\.nav-mobile-actions \{ display: grid; \}/.test(css));
check('sticky mobile quote bar displays at phone breakpoint', /@media \(max-width: 768px\)[\s\S]*\.mobile-quote-bar\.show \{ display: flex; \}/.test(css));
check('desktop nav actions hide on phone', /\.nav-links, \.nav-cta, \.nav-actions \{ display: none; \}/.test(css));
check('cart badges are shared', /updateCartBadges/.test(nav) && /SEMNav\.updateCartBadges/.test(main) && /SEMNav\.updateCartBadges/.test(productRuntime));
check('global cart drawer exists', /global-cart-drawer/.test(main) && /global-cf-name/.test(main) && /global-wa-btn/.test(main));
check('product cart drawer exists', /cart-drawer/.test(productRuntime) && /cf-name/.test(productRuntime) && /wa-btn/.test(productRuntime));
check('product modal add-to-cart exists', /pm-add-cart/.test(productRuntime) && /Add to Cart/.test(productRuntime));
check('cart item visual uses fan icon', /ui-icon-fan/.test(css) && /cart-item-icon/.test(productRuntime) && /global-cart-item-icon/.test(css));
check('product fallback artwork is category aware', /productFallback/.test(productRuntime) && /prod-fallback/.test(productRuntime) && /productCardFallback/.test(main));
check('usage cards reuse category fallback artwork', /popularCard[\s\S]*productCardFallback\(product\.category\)/.test(main) && /resultCard[\s\S]*productCardFallback\(product\.category\)/.test(main));
check('products page loads extracted stylesheet', /href="\/css\/products\.css(?:\?[^"']*)?"/.test(products) && /prod-grid/.test(productCss));
check('products page loads extracted runtime', /src="\/js\/products-page\.js(?:\?[^"']*)?"/.test(products));
check('products page has no inline style block', !/<style[\s>]/i.test(products));
check('quote dialogs expose modal semantics', /global-cart-drawer" role="dialog"/.test(main) && /pmodal" role="dialog"/.test(productRuntime) && /cart-drawer" role="dialog"/.test(productRuntime));
check('mobile menu exposes expanded state', /aria-expanded/.test(nav) && /aria-controls/.test(nav));
check('quote summary can edit saved details', /data-global-edit-details/.test(main) && /data-edit-details/.test(productRuntime));
check('product SEO links and schema are generated', /product-seo-links/.test(productRuntime) && /injectProductItemListSchema/.test(productRuntime) && /ItemList/.test(productRuntime));
check('product cart empty state has browse action', /data-browse-products/.test(productRuntime) && /cart-empty-btn/.test(productCss));
check('mobile compare cards are generated', /buildCompareCards/.test(productRuntime) && /compare-card-list/.test(productCss) && /@media \(max-width: 560px\)[\s\S]*\.compare-table \{ display:none; \}/.test(productCss));
check('compare bar shows selected product chips', /compare-chip-row/.test(productRuntime) && /compare-chip/.test(productCss) && /getProductById\(id\)/.test(productRuntime));
check('compare modal restores focus', /lastCompareTrigger/.test(productRuntime) && /compare-close'\)\.focus/.test(productRuntime));
check('combined product finder supports models', /Find a Product/.test(products) && /SDB 133/.test(products) && /modelText/.test(productRuntime));
check('guided selector uses catalogue requirements', /guided-selector-form/.test(products) && /guideMatches/.test(productRuntime));
check('fan selection helper is removed', !/selector-panel|sel-airflow|scoreSelectorProduct|model-finder-input/.test(productRuntime + productCss));
check('customer details persist globally', /sem-customer-details/.test(main) && /saveCustomerDetails/.test(main) && /restoreCustomerDetails/.test(main));
check('customer details persist on products page', /sem-customer-details/.test(productRuntime) && /saveCustomerDetails/.test(productRuntime) && /restoreCustomerDetails/.test(productRuntime));

const routePairs = [
  ['about.html', 'about/index.html'],
  ['products.html', 'products/index.html'],
  ['applications.html', 'applications/index.html'],
  ['downloads.html', 'downloads/index.html'],
  ['distributors.html', 'distributors/index.html'],
  ['contact.html', 'contact/index.html']
];

routePairs.forEach(([source, target]) => {
  check(`${target} matches ${source}`, read(source) === read(target));
});

const failed = checks.filter(item => !item.ok);
checks.forEach(item => {
  console.log(`${item.ok ? 'OK ' : 'ERR'} ${item.name}`);
});

if (failed.length) {
  console.error(`\n${failed.length} mobile smoke check(s) failed.`);
  process.exit(1);
}

console.log(`\n${checks.length} mobile smoke checks passed.`);
