#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const checks = [];

function check(name, ok) {
  checks.push({ name, ok: Boolean(ok) });
}

const css = read('css/style.css');
const nav = read('js/nav.js');
const main = read('js/main.js');
const products = read('products.html');
const pages = [
  'index.html',
  'about.html',
  'products.html',
  'applications.html',
  'downloads.html',
  'distributors.html',
  'contact.html',
  '404.html'
];

pages.forEach(page => {
  const html = read(page);
  check(`${page} loads shared nav`, html.includes('<script src="/js/nav.js"></script>'));
  check(`${page} has mobile nav container`, html.includes('class="nav-mobile"'));
  check(`${page} has hamburger`, html.includes('class="nav-hamburger"'));
});

check('mobile actions are generated by nav.js', /nav-mobile-actions/.test(nav) && /icon\('cart'\)/.test(nav) && /Get a Quote/.test(nav));
check('mobile actions display at phone breakpoint', /@media \(max-width: 768px\)[\s\S]*\.nav-mobile-actions \{ display: grid; \}/.test(css));
check('desktop nav actions hide on phone', /\.nav-links, \.nav-cta, \.nav-actions \{ display: none; \}/.test(css));
check('cart badges are shared', /updateCartBadges/.test(nav) && /SEMNav\.updateCartBadges/.test(main) && /SEMNav\.updateCartBadges/.test(products));
check('global cart drawer exists', /global-cart-drawer/.test(main) && /global-cf-name/.test(main) && /global-wa-btn/.test(main));
check('product cart drawer exists', /cart-drawer/.test(products) && /cf-name/.test(products) && /wa-btn/.test(products));
check('product modal add-to-cart exists', /pm-add-cart/.test(products) && /Add to Cart/.test(products));
check('cart item visual uses fan icon', /ui-icon-fan/.test(css) && /cart-item-icon/.test(products) && /global-cart-item-icon/.test(css));
check('customer details persist globally', /sem-customer-details/.test(main) && /saveCustomerDetails/.test(main) && /restoreCustomerDetails/.test(main));
check('customer details persist on products page', /sem-customer-details/.test(products) && /saveCustomerDetails/.test(products) && /restoreCustomerDetails/.test(products));

const routePairs = [
  ['about.html', 'about/index.html'],
  ['products.html', 'products/index.html'],
  ['applications.html', 'applications/index.html'],
  ['downloads.html', 'downloads/index.html'],
  ['distributors.html', 'distributors/index.html'],
  ['contact.html', 'contact/index.html']
];

routePairs.forEach(([source, target]) => {
  check(`${target} matches ${source}`, read(source) === read(target));
});

const failed = checks.filter(item => !item.ok);
checks.forEach(item => {
  console.log(`${item.ok ? 'OK ' : 'ERR'} ${item.name}`);
});

if (failed.length) {
  console.error(`\n${failed.length} mobile smoke check(s) failed.`);
  process.exit(1);
}

console.log(`\n${checks.length} mobile smoke checks passed.`);
